name: PyPI Release

# We only really want this to happen manually
on:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    # Build the project
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    - name: Build package 
      run: |
        python -m build
    
    # Publish (https://github.com/pypa/gh-action-pypi-publish)
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        print_hash: true
