# Run the unittest tests found in this repository.


name: Unit Tests

on:

  # Run tests when this workflow is updated
  push:
    paths:
      - '.github/workflows/tests.yml'

  # Schedule testing every dat at 00:00 UTC (~6pm CST)
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
  
    # OS and Python versions we want to test
    strategy:
      matrix:
        python-version: ["3.10"]
        operating-system: [windows-latest, ubuntu-latest, macos-latest]
        
    # Build for the OS and Py version
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Unit Tests
        run: python -m unittest discover -v -s ./tests -p test_*.py
